/*
The core of the issue is the asteroid/comet spawner passing a random int for the "id" argument of the ProtoVessel.CreatePartNode() method.
This id is affected to the part.flightId field, which must be unique game-wide and should have been generated by calling 
ShipConstruction.GetUniqueFlightID(). Failing to produce an unique flightId result in various issues, especially with mods as they often
rely on that id.

Note that by fixing this, we replace how the asteroid/comet "seed" is generated, which technically affect further calls to UnityEngine.Random(),
but this shouldn't have any effect on the actual randomness/distribution of the generated stuff.
*/

using System;
using System.Collections.Generic;
using HarmonyLib;
using UnityEngine;

namespace KSPCommunityFixes.BugFixes
{
    class AsteroidSpawnerUniqueFlightId : BasePatch
    {
        protected override Version VersionMin => new Version(1, 8, 0);

        protected override void ApplyPatches(ref List<PatchInfo> patches)
        {
            patches.Add(new PatchInfo(
                PatchMethodType.Prefix,
                AccessTools.Method(typeof(ScenarioDiscoverableObjects), nameof(ScenarioDiscoverableObjects.SpawnAsteroid)),
                this));
        }

        static bool ScenarioDiscoverableObjects_SpawnAsteroid_Prefix(ScenarioDiscoverableObjects __instance)
        {
            uint flightId;
            do
            {
                flightId = ShipConstruction.GetUniqueFlightID(HighLogic.CurrentGame.flightState);
            } 
            while (flightId > int.MaxValue);

            int seed = (int)flightId;
            UnityEngine.Random.InitState(seed);
            __instance.lastSeed = seed;

            if (__instance.ReachedBody("Dres") && Mathf.Abs(seed % 3) == 0)
                __instance.SpawnDresAsteroid(seed);
            else
                __instance.SpawnHomeAsteroid(seed);

            return false;
        }
    }

    class CometSpawnerUniqueFlightId : BasePatch
    {
        protected override Version VersionMin => new Version(1, 10, 0);

        protected override void ApplyPatches(ref List<PatchInfo> patches)
        {
            patches.Add(new PatchInfo(
                    PatchMethodType.Prefix,
                    AccessTools.Method(typeof(ScenarioDiscoverableObjects), nameof(ScenarioDiscoverableObjects.SpawnComet), new Type[] {typeof(CometOrbitType) }),
                    this));
        }

        static bool ScenarioDiscoverableObjects_SpawnComet_Prefix(ScenarioDiscoverableObjects __instance, CometOrbitType cometType)
        {
            uint flightId;
            do
            {
                flightId = ShipConstruction.GetUniqueFlightID(HighLogic.CurrentGame.flightState);
            }
            while (flightId > int.MaxValue);

            int seed = (int)flightId;

            UnityEngine.Random.InitState(seed);
            __instance.lastSeed = seed;
            double lifeTime = UnityEngine.Random.Range(__instance.minUntrackedLifetime, __instance.maxUntrackedLifetime) * 24.0 * 60.0 * 60.0;
            double lifeTimeMax = __instance.maxUntrackedLifetime * 24.0 * 60.0 * 60.0;
            UntrackedObjectClass randomObjClass = cometType.GetRandomObjClass();
            CometDefinition cometDef = CometManager.GenerateDefinition(cometType, randomObjClass, seed);
            Orbit o = cometType.CalculateHomeOrbit();
            DiscoverableObjectsUtil.SpawnComet("UnknownComet", o, cometDef, flightId, randomObjClass, lifeTime, lifeTimeMax, false, 0f);
            Debug.Log("[CometSpawner]: New object found near " + FlightGlobals.GetHomeBodyName());

            return false;
        }
    }
}
