/*
The core of the issue is the asteroid/comet spawner passing a random int for the "id" argument of the ProtoVessel.CreatePartNode() method.
This id is affected to the part.flightId field, which must be unique game-wide and should have been generated by calling 
ShipConstruction.GetUniqueFlightID(). Failing to produce an unique flightId result in various issues, especially with mods as they often
rely on that id.

Note that by fixing this, we replace how the asteroid/comet "seed" is generated, which technically affect further calls to UnityEngine.Random(),
but this shouldn't have any effect on the actual randomness/distribution of the generated stuff.
*/

using System;
using System.Collections.Generic;
using HarmonyLib;
using KSP.UI.Screens;

namespace KSPCommunityFixes.BugFixes
{
    class DepartmentHeadImage : BasePatch
    {
        protected override Version VersionMin => new Version(1, 8, 0);

        protected override void ApplyPatches(List<PatchInfo> patches)
        {
            patches.Add(new PatchInfo(
                PatchMethodType.Postfix,
                AccessTools.Method(typeof(Administration), "AddKerbalListItem"),
                this));
        }

        static void Administration_AddKerbalListItem_Postfix(Administration __instance, ref Strategies.DepartmentConfig dep)
        {
            if (dep.AvatarPrefab != null || dep.HeadImage == null)
                return;

            KSP.UI.UIListItem item = __instance.scrollListKerbals.GetUilistItemAt(__instance.scrollListKerbals.Count - 1);
            KerbalListItem kerbal = item.GetComponent<KerbalListItem>();
            kerbal.kerbalImage.texture = dep.HeadImage;
            kerbal.kerbalImage.material = kerbal.kerbalImage.defaultMaterial;
        }
    }
}
